#!/usr/bin/env bash
# shellcheck disable=SC2034

[[ -n "${VPS_WIREGUARD_COMMON_SH:-}" ]] && return 0
VPS_WIREGUARD_COMMON_SH=1

REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CLIENTS_DIR="${SCRIPT_DIR}/clients"

WG_IF_DEFAULT="wg0"
WG_PORT_DEFAULT="51820"
WG_NET_DEFAULT="10.8.0.0/24"
WG_NET6_DEFAULT="fd42:42:42::/64"
WG_SERVER_IP_DEFAULT="10.8.0.1"
WG_SERVER_IP6_DEFAULT="fd42:42:42::1"
WG_DIR="/etc/wireguard"
SYSCTL_FILE="/etc/sysctl.d/99-wireguard.conf"
WG_PREFIX="24"
WG_PREFIX6="64"

WG_FAMILY_NAME="WireGuard"
WG_FAMILY_TOOL="wg"
WG_FAMILY_QUICK="wg-quick"
WG_FAMILY_DIR="${WG_DIR}"
WG_FAMILY_DEFAULT_IF="${WG_IF_DEFAULT}"
WG_FAMILY_CLIENT_PREFIX="wg0"
WG_FAMILY_DEFAULT_PORT="${WG_PORT_DEFAULT}"
WG_FAMILY_DEFAULT_NET="${WG_NET_DEFAULT}"
WG_FAMILY_DEFAULT_NET6="${WG_NET6_DEFAULT}"
