# Client: :CLIENT_NAME:
[Interface]
Address = :CLIENT_IP:/32, :CLIENT_IP6:/128
PrivateKey = :CLIENT_KEY:
DNS = 1.1.1.1, 8.8.8.8
MTU = :AWG_MTU:

Jc = :AWG_JC:
Jmin = :AWG_JMIN:
Jmax = :AWG_JMAX:
S1 = :AWG_S1:
S2 = :AWG_S2:
S3 = :AWG_S3:
S4 = :AWG_S4:
H1 = :AWG_H1:
H2 = :AWG_H2:
H3 = :AWG_H3:
H4 = :AWG_H4:
I1 = :AWG_I1:
# I2 =
# I3 =
# I4 =
# I5 =

[Peer]
PublicKey = :SERVER_PUB_KEY:
PresharedKey = :PRESHARED_KEY:
Endpoint = :SERVER_ENDPOINT:
# Route only VPN traffic through VPN
# AllowedIPs = :SERVER_NET:, :SERVER_NET6:
# Route all traffic through VPN
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
