[Interface]
PrivateKey = :SERVER_PRIV_KEY:
Address = :SERVER_IP:/:SERVER_PREFIX:, :SERVER_IP6:/:SERVER_PREFIX6:
ListenPort = :SERVER_PORT:
MTU = :AWG_MTU:
SaveConfig = false

Jc = :AWG_JC:
Jmin = :AWG_JMIN:
Jmax = :AWG_JMAX:
S1 = :AWG_S1:
S2 = :AWG_S2:
S3 = :AWG_S3:
S4 = :AWG_S4:
H1 = :AWG_H1:
H2 = :AWG_H2:
H3 = :AWG_H3:
H4 = :AWG_H4:
I1 = :AWG_I1:
# I2 =
# I3 =
# I4 =
# I5 =

# PostUp = iptables -t nat -A PREROUTING -i %i -p udp --dport 53 -j DNAT --to-destination :SERVER_IP::53
# PostUp = iptables -t nat -A PREROUTING -i %i -p tcp --dport 53 -j DNAT --to-destination :SERVER_IP::53

PostUp = iptables -A FORWARD -i %i -o :SERVER_IF: -j ACCEPT
PostUp = iptables -A FORWARD -i :SERVER_IF: -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
PostUp = ip6tables -A FORWARD -i %i -o :SERVER_IF: -j ACCEPT
PostUp = ip6tables -A FORWARD -i :SERVER_IF: -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

PostUp = iptables -t nat -A POSTROUTING -s :SERVER_NET: -o :SERVER_IF: -j MASQUERADE
PostUp = ip6tables -t nat -A POSTROUTING -s :SERVER_NET6: -o :SERVER_IF: -j MASQUERADE

# PreDown = iptables -t nat -D PREROUTING -i %i -p udp --dport 53 -j DNAT --to-destination :SERVER_IP::53
# PreDown = iptables -t nat -D PREROUTING -i %i -p tcp --dport 53 -j DNAT --to-destination :SERVER_IP::53

PreDown = iptables -D FORWARD -i %i -o :SERVER_IF: -j ACCEPT
PreDown = iptables -D FORWARD -i :SERVER_IF: -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
PreDown = ip6tables -D FORWARD -i %i -o :SERVER_IF: -j ACCEPT
PreDown = ip6tables -D FORWARD -i :SERVER_IF: -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

PreDown = iptables -t nat -D POSTROUTING -s :SERVER_NET: -o :SERVER_IF: -j MASQUERADE
PreDown = ip6tables -t nat -D POSTROUTING -s :SERVER_NET6: -o :SERVER_IF: -j MASQUERADE
