#!/usr/bin/env bash
# shellcheck disable=SC2034

[[ -n "${VPS_AMNEZIA_COMMON_SH:-}" ]] && return 0
VPS_AMNEZIA_COMMON_SH=1

REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CLIENTS_DIR="${SCRIPT_DIR}/clients"

AWG_IF_DEFAULT="awg0"
AWG_PORT_DEFAULT="52820"
AWG_NET_DEFAULT="10.9.0.0/24"
AWG_NET6_DEFAULT="fd52:52:52::/64"
AWG_SERVER_IP_DEFAULT="10.9.0.1"
AWG_SERVER_IP6_DEFAULT="fd52:52:52::1"
AWG_DIR="/etc/amnezia/amneziawg"
SYSCTL_FILE="/etc/sysctl.d/99-amneziawg.conf"
AWG_PREFIX="24"
AWG_PREFIX6="64"

WG_FAMILY_NAME="AmneziaWG"
WG_FAMILY_TOOL="awg"
WG_FAMILY_QUICK="awg-quick"
WG_FAMILY_DIR="${AWG_DIR}"
WG_FAMILY_DEFAULT_IF="${AWG_IF_DEFAULT}"
WG_FAMILY_CLIENT_PREFIX="awg0"
WG_FAMILY_DEFAULT_PORT="${AWG_PORT_DEFAULT}"
WG_FAMILY_DEFAULT_NET="${AWG_NET_DEFAULT}"
WG_FAMILY_DEFAULT_NET6="${AWG_NET6_DEFAULT}"
